### ISSUE TITLE
Registry Review 0.4.0

### ISSUE THREAD

**Issue by ngokevin** [takahirox/aframe-deferred-renderer#1]
**Required:**

- None

**Suggested:**

- I would recommend not calling a handler (`.update()`) directly from another handler (`.play()`). Rather, I would factor out the method, and call it from both:

```js
update() {
  this.setupDeferredRenderer();
},

play() {
  this.setupDeferredRenderer(); 
},

setupDeferredRenderer() {
  // ...
}
```

- Minor nit in the README. Make the script URLs absolute rather than relative, so it's easier to copy/paste. You can also add syntax highlighting:

```
// ```html
// <code></code>
// ```
```

**Comment by takahirox** [comment]
Thanks for the comment. I'll update!

**Comment by takahirox** [comment]
Updated.
